server {
    listen 80 default_server;

    # extensions

    location /otp {
		return 301 /otp/;
	}
	location /otp/ {
		proxy_pass http://otp:8080;
	}
	location / { 
		proxy_pass http://otp:8080;
	}

	# location /photon {
	# 	return 301 /photon/;
	# }
	# location /photon/ {
	# 	proxy_pass http://photon:2322/;
	# }

}